### PR TITLE
ci(): add e2e playwright test

### PR DESCRIPTION
**Pull request by ShaMan123**
```bash
   npm i
   npx playwright install --with-deps chromium
   ```

### CODE REVIEW

**Review by ShaMan123 — COMMENTED** [review]
not working for some reason

**Comment by Dexus** [comment]
I will check this later, if you do not have luck to fix it.

**Comment by Dexus** [comment]
Possible : https://playwright.dev/docs/api/class-electron the known issue? Would make sense for me.

Will check later.

**Review by ShaMan123 — COMMENTED** [review]
Passing!
Ubuntu 24 issue resolved

**Comment by ShaMan123** [comment]
**Squash** and merge please

**Comment by Dexus** [comment]
Thank you @ShaMan123

**Comment by ShaMan123** [comment]
My pleasure

**Pull request merged**
